version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./db_data/:/var/lib/mysql
    ports:
      - "33060:3306"